site_name: Hubzilla Docs
theme:
  name: material
  logo: assets/logo.png 
  favicon: assets/logo.png
  previous: fontawesome/solid/angle-left
  next: fontawesome/solid/angle-right  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy
    - search.suggest
    - toc.integrate
    - navigation.top    
  icon:
    repo: fontawesome/brands/github

repo_name: saiwal/hubzilla-docs
repo_url: https://github.com/saiwal/hubzilla-docs

plugins:
  - search

extra:
  version:
    provider: mike
    alias: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables


