site_name: Hubzilla Docs
theme:
  name: material
  logo: assets/logo.png 
  favicon: assets/logo.png
  previous: fontawesome/solid/angle-left
  next: fontawesome/solid/angle-right  
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.code.copy
    - search.suggest
  icon:
    repo: fontawesome/brands/github

repo_name: saiwal/hubzilla-docs
repo_url: https://github.com/saiwal/hubzilla-docs

plugins:
  - search

extra:
  version:
    provider: mike
    alias: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

# Page tree
nav:
  - Home: 
    - index.md 
    - About Hubzilla Project: 
      - about/project/index.md
      - Credits: about/project/credits.md
      - Privacy: about/gdpr.md
      - Release Notes: about/release.md 
      - Contributing: about/contribute.md
  - Getting Started: start/
#     - start/index.md
#     - Preparation: start/prep.md
#     - Manual Installation: start/manual_install.md 
#     - Script install: start/script_install.md 
#     - Docker deployment: start/docker.md     
#   - Member Guide: 'member/'
#   - Administrator Guide:
#     - admin/index.md 
#     - Directory: admin/primary_directory.md
#     - Hub Snapshots: admin/hub_snapshots.md
#     - Widgets: admin/widgets.md
#   - Developers Guide:
#     - dev/index.md 
#     - Database Tables:
#       - dev/database/index.md 
#       - abconfig: dev/database/db_abconfig.md
#       - abook: dev/database/db_abook.md 
#       - account: dev/database/db_account.md
#       - addon: dev/database/db_addon.md
#       - app: dev/database/db_app.md
#       - attach: dev/database/db_attach.md
#       - auth_codes: dev/database/db_auth_codes.md
#       - cache: dev/database/db_cache.md
#       - cal: dev/database/db_cal.md
#       - channel: dev/database/db_channel.md
#       - chat: dev/database/db_chat.md
#       - chatpresence: dev/database/db_chatpresence.md
#       - chatroom: dev/database/db_chatroom.md
#       - clients: dev/database/db_clients.md
#       - config: dev/database/db_config.md
#       - conv: dev/database/db_conv.md
#       - event : dev/database/db_event.md
#       - pgrp_member : dev/database/db_pgrp_member.md
#       - pgrp : dev/database/db_pgrp.md
#       - hook : dev/database/db_hook.md
#       - hubloc : dev/database/db_hubloc.md
#       - iconfig : dev/database/db_iconfig.md
#       - issue : dev/database/db_issue.md
#       - item : dev/database/db_item.md
#       - item_id : dev/database/db_item_id.md
#       - likes : dev/database/db_likes.md
#       - mail : dev/database/db_mail.md
#       - menu : dev/database/db_menu.md
#       - menu_items : dev/database/db_menu_items.md
#       - notify : dev/database/db_notify.md
#       - obj : dev/database/db_obj.md
#       - outq : dev/database/db_outq.md
#       - pconfig : dev/database/db_pconfig.md
#       - photo : dev/database/db_photo.md
#       - poll : dev/database/db_poll.md
#       - poll_elm : dev/database/db_poll_elm.md
#       - profdef : dev/database/db_profdef.md
#       - profext : dev/database/db_profext.md
#       - profile : dev/database/db_profile.md
#       - profile_check : dev/database/db_profile_check.md
#       - register : dev/database/db_register.md
#       - session : dev/database/db_session.md
#       - shares : dev/database/db_shares.md
#       - sign : dev/database/db_sign.md
#       - site : dev/database/db_site.md
#       - source : dev/database/db_source.md
#       - sys_perms : dev/database/db_sys_perms.md
#       - term : dev/database/db_term.md
#       - tokens: dev/database/db_tokens.md
#       - updates : dev/database/db_updates.md
#       - verify : dev/database/db_verify.md
#       - vote : dev/database/db_vote.md
#       - xchan: dev/database/db_xchan.md
#       - xchat : dev/database/db_xchat.md
#       - xconfig : dev/database/db_xconfig.md
#       - xign : dev/database/db_xign.md
#       - xlink : dev/database/db_xlink.md
#       - xperm: dev/database/db_xperm.md
#       - xprof : dev/database/db_xprof.md
#       - xtag: dev/database/db_xtag.md
#     - Derived Theme: dev/themes/index.md 
#     - Filesync and Clone : dev/filesync.md 
#     - Plugins: dev/plugins/index.md 
#     - Widgets: dev/widgets/index.md
#     - Schema system: dev/schema.md 
#     - Translating: dev/translations.md 
#     - Zot: dev/zot.md 
#   - API:
#     - api/index.md
#
